### PR TITLE
500 error page matches new theme

### PR DESCRIPTION
**Pull request by abr-storm**
This PR updates the error page in the repo, after it's approved I will upload `error-pages` to AWS so it starts getting served by the app.

image
image

### CODE REVIEW

**Comment by abr-storm** [comment]
@msquance-stem Is there a way we can add an exception in Sonar for this bundled css file? It's just complaining about the webpack output which I'm not sure is helpful.

**Comment by abr-storm** [comment]
Hi @STEMSam, are you happy that this matches your design?

**Comment by STEMSam** [comment]
Hi @abr-storm Nice to meet you. That looks great, thank you very much. Happy to approve from the UI side of things

**Comment by markjs** [comment]
@abr-storm Is there anything we can do to reduce that CSS file? There's no way we need 16k lines of CSS for error pages 😬

**Review by barrywoolgar — APPROVED** [review]
Looks good to me, thanks Alex

**Pull request merged**
