### PR TITLE
Text update

### PR DESCRIPTION
**Pull request by nyashamaphosa**
## Status

* Current Status: Ready for review
* Review App link(s): *populate this with links to the relevant parts of the review app*
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2446
* 
## What's changed?

update text in senior leaders page
## Steps to perform after deploying to production

### CODE REVIEW

**Review by Caleb-T-Owens — CHANGES_REQUESTED** [review]
Hi! In the ticket you link here, it links to this page: https://teachcomputing.org/secondary-senior-leaders and refers to the copy in this card: Screenshot 2023-09-06 at 13 31 16

And requires the changing of the CTA as well. 


It doesn't refer to changing this copy? Have you perhaps pushed the wrong code or linked the wrong ticket?

**Comment by nyashamaphosa** [comment]
> Hi! In the ticket you link here, it links to this page: https://teachcomputing.org/secondary-senior-leaders and refers to the copy in this card: Screenshot 2023-09-06 at 13 31 16
> 
> And requires the changing of the CTA as well.
> 
> It doesn't refer to changing this copy? Have you perhaps pushed the wrong code or linked the wrong ticket?



> Hi! In the ticket you link here, it links to this page: https://teachcomputing.org/secondary-senior-leaders and refers to the copy in this card: Screenshot 2023-09-06 at 13 31 16
> 
> And requires the changing of the CTA as well.
> 
> It doesn't refer to changing this copy? Have you perhaps pushed the wrong code or linked the wrong ticket?

@Caleb-T-Owens Ahhh yes i see, i overlooked this one sorry. resolved now thank you.

**Review by Caleb-T-Owens — CHANGES_REQUESTED** [review]
I believe you need to change this line too according to the ticket https://github.com/NCCE/teachcomputing.org/pull/1786/files#diff-55b0b990f8b2a9286d19f0728be83293ab41ce9e9d01ac8c601736349536b323R57

@Caleb-T-Owens Resolved this one to thank you

**Review by Caleb-T-Owens — APPROVED** [review]
LGTM

**Pull request merged**
