### PR TITLE
seeds courses

### PR DESCRIPTION
**Pull request by nyashamaphosa**
## Status

* Current Status: Ready for review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2476

## What's changed?

Seeds courses

### CODE REVIEW

**Review by Caleb-T-Owens — CHANGES_REQUESTED** [review]
Could you add in the quantity of credits for these activities

**Comment by nyashamaphosa** [comment]
> Could you add in the quantity of credits for these activities

resolved thank you

**Comment by Caleb-T-Owens** [comment]
@nyashamaphosa I've had a discussion with Dapo about these courses and we're not sure that they're available just yet, so we're going to want to just hold off until we've got a better idea of how these multi-part CPDs should behave from Dynamics

**Comment by Caleb-T-Owens** [comment]
See ticket for closure reason

**Pull request closed without merging**
