### PR TITLE
Add video to i belong page

### PR DESCRIPTION
**Pull request by abr-storm**
image

### CODE REVIEW

**Comment by abr-storm** [comment]
Is this what you were expecting @vickymg? I've kept the column layout as it was, but considering the dimensions of the video we could also put on top of or below the text.

**Comment by vickymg** [comment]
@STEMSamwondering if you have thoughts on this one - we're replacing the image on the I Belong landing page with this video, however, it's a fair bit wider so wondering if the text might look better above or below the video - do you have a preference?

**Comment by Caleb-T-Owens** [comment]
Hi there! I was taking a look and one possibility could be having the video smaller like this:
Screenshot 2024-03-07 at 14 18 29

Wrapping down on mobile:
Screenshot 2024-03-07 at 14 18 46

**Comment by Caleb-T-Owens** [comment]
@abr-storm would you like me to make this change?

**Comment by abr-storm** [comment]
> @abr-storm would you like me to make this change?

Yeah feel free to pick this up if you want

**Review by Caleb-T-Owens — APPROVED** [review]

**Pull request merged**
