### PR TITLE
Feature: only one course for certs

### PR DESCRIPTION
**Pull request by dcorking**
## Status

* Current Status: Ready for front-end & tech review
* Review App link(s): *not yet deployed*
  * https://qa.teachcomputing.org/certificate/secondary-certificate (note: need to have completed the accelerator and enroled)
  * https://qa.teachcomputing.org/certificate/primary-certificate (note: need to have enroled)
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2287

## Review progress:

- [x] Front-end review completed
- [x] Tech review completed

## What's changed?

Simplify primary and secondary certificates to require only 1 eligible course rather than 1 of each kind (live and online)

- https://docs.google.com/document/d/1rifqkHlOsnS8iRv3pKM9dCuAqc53jaRT/edit
- https://docs.google.com/document/d/1tVxTLG6vBzir5rO0vRwSvMCwlnEKFCUh/edit

## Steps to perform after deploying to production

Run
```
heroku run  bin/rails update_certificate_data && bin/rails db:seed --app=teachcomputing-production
```

### CODE REVIEW

**Comment by dcorking** [comment]
some screenshots
Screenshot 2023-03-14 at 15 52 20
Screenshot 2023-03-14 at 15 52 36
Screenshot 2023-03-14 at 16 04 39

**Comment by dcorking** [comment]
copy updated to 
>  Complete any course from this certificate 
Screenshot 2023-03-16 at 12 44 29

**Comment by dcorking** [comment]
@danhalson I noticed that line 86 of update_certificate_data.rake wipes all the courses from the programmes and doesn't replace them. Is it sufficient for me to run db:seed afterwards to get everything working again?

**Review by danhalson — COMMENTED** [review]
all looks good to me, though it would be remiss of me not to point out that I can't see a mechanism in place to update the current groupings, they probably just need removing and re-seeding in a similar way to how you've done the pathway activities.

**Comment by danhalson** [comment]
> @danhalson I noticed that line 86 of update_certificate_data.rake wipes all the courses from the programmes and doesn't replace them. Is it sufficient for me to run db:seed afterwards to get everything working again?

ah, sorry just spotted this - yes that will do the trick 👍

**Pull request merged**
